# Generated by Django 5.1.4 on 2024-12-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='job_type',
            field=models.ManyToManyField(blank=True, related_name='qsn_job_types', to='interview.jobtype'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='job_type',
            field=models.ManyToManyField(blank=True, related_name='user_qsn_job_types', to='interview.jobtype'),
        ),
    ]
